name: pet_help
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_xlider: ^3.4.0
  sticky_headers: "^0.1.8"
  flutter_material_color_picker: ^1.0.3
  address_picker:
    git:
      url: git://github.com/vulemicom/address_picker_flutter.git
  flutter:
    sdk: flutter
  flutter_number_picker:
      git: https://github.com/phuongtinhbien/flutter_number_picker.git

 



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  google_sign_in: ^4.5.5
#  firebase_auth: ^0.18.1+2
  google_maps_flutter: ^0.5.11+1
  flutter_polyline_points: ^0.1.0
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.0
  line_icons: ^0.2.0
  flutter_slider_drawer: ^1.0.3
  image: ^2.1.18
  flutter_login: ^1.0.14
  loadmore: ^1.0.4
  multi_image_picker: ^4.7.14
  carousel_pro: ^1.0.0
  firebase_storage: ^3.1.1
  cloud_firestore: ^0.13.0+1
  loading_animations: "^2.1.0"
  image_picker: ^0.6.7+11
  geolocator: ^5.3.1
  pp_local_notifications: ^0.0.1
  flutter_launcher_icons: ^0.8.1
  splashscreen: ^1.2.0
  location: ^2.5.0
  responsive_grid: ^1.2.1+1
  flutter_facebook_login: ^3.0.0
  flutter_auth_buttons: ^0.10.0


flutter-icon:
  image_path: "src/icon/logoApp.png"
  iso: true
  android : true
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - src/image/chat-background-1.jpg
    - src/image/MapGG.jpg
    - src/image/avt.jpg
    - src/image/background.jpg
    - src/image/welcomeScreen.png
    - src/image/cmnd1.png
    - src/image/cmnd2.png
    - src/image/meo1.jpg
    - src/image/cat2.jpg
    - src/image/cat3.jpg
    - src/image/cat4.jpg
    - src/image/cat_5.jpg
    - src/image/cat6.jpg
    - src/image/download.jpg
    - src/image/download (1).jpg
    - src/image/rescue_cat1.jpg
    - src/image/rescue_cat2.jpg
    - src/image/rescue_cat3.jpg
    - src/image/nga.jpg
    - src/image/lost_puppyjpg.jpg
    - src/image/samoyed.jpg
    - src/image/pet_4.jpg
    - src/image/pet_5.jpg
    - src/image/pet_6.jpg
    - src/image/cat_mouth1.jpg
    - src/image/cat_mouth2.jpg
    - src/image/cat_mouth3.jpg
    - src/image/dog_attack.jpg
    - src/image/lost_kitty.jpg
    - src/icon/contact.png
    - src/icon/cat.png
    - src/icon/adopt.png
    - src/icon/profile.png
    - src/icon/pet-house.png
    - src/icon/post.png
    - src/icon/logout.png
    - src/icon/logoCute.png
    - src/icon/google_logo.png
    - src/data/pet.json
    - src/data/contact.json

  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
